//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.ConsoleClient.DataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ShowStatus", ReplyAction="http://tempuri.org/IDataService/ShowStatusResponse")]
        Warehouse.ConsoleClient.DataService.ShowStatusResponse ShowStatus(Warehouse.ConsoleClient.DataService.ShowStatusRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ShowStatus", ReplyAction="http://tempuri.org/IDataService/ShowStatusResponse")]
        System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.ShowStatusResponse> ShowStatusAsync(Warehouse.ConsoleClient.DataService.ShowStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/PlaceContainers", ReplyAction="http://tempuri.org/IDataService/PlaceContainersResponse")]
        Warehouse.ConsoleClient.DataService.PlaceContainersResponse PlaceContainers(Warehouse.ConsoleClient.DataService.PlaceContainersRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/PlaceContainers", ReplyAction="http://tempuri.org/IDataService/PlaceContainersResponse")]
        System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.PlaceContainersResponse> PlaceContainersAsync(Warehouse.ConsoleClient.DataService.PlaceContainersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/FreeContainers", ReplyAction="http://tempuri.org/IDataService/FreeContainersResponse")]
        Warehouse.ConsoleClient.DataService.FreeContainersResponse FreeContainers(Warehouse.ConsoleClient.DataService.FreeContainersRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/FreeContainers", ReplyAction="http://tempuri.org/IDataService/FreeContainersResponse")]
        System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.FreeContainersResponse> FreeContainersAsync(Warehouse.ConsoleClient.DataService.FreeContainersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ShowStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ShowStatusRequest {
        
        public ShowStatusRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ShowStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ShowStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ShowStatusResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool success;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string exceptionString;
        
        public ShowStatusResponse() {
        }
        
        public ShowStatusResponse(string ShowStatusResult, bool success, string exceptionString) {
            this.ShowStatusResult = ShowStatusResult;
            this.success = success;
            this.exceptionString = exceptionString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PlaceContainers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PlaceContainersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ushort N;
        
        public PlaceContainersRequest() {
        }
        
        public PlaceContainersRequest(ushort N) {
            this.N = N;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PlaceContainersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PlaceContainersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string PlaceContainersResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool success;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string exceptionString;
        
        public PlaceContainersResponse() {
        }
        
        public PlaceContainersResponse(string PlaceContainersResult, bool success, string exceptionString) {
            this.PlaceContainersResult = PlaceContainersResult;
            this.success = success;
            this.exceptionString = exceptionString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FreeContainers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FreeContainersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ushort N;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string hangarId;
        
        public FreeContainersRequest() {
        }
        
        public FreeContainersRequest(ushort N, string hangarId) {
            this.N = N;
            this.hangarId = hangarId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FreeContainersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FreeContainersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string FreeContainersResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool success;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string exceptionString;
        
        public FreeContainersResponse() {
        }
        
        public FreeContainersResponse(string FreeContainersResult, bool success, string exceptionString) {
            this.FreeContainersResult = FreeContainersResult;
            this.success = success;
            this.exceptionString = exceptionString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : Warehouse.ConsoleClient.DataService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<Warehouse.ConsoleClient.DataService.IDataService>, Warehouse.ConsoleClient.DataService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Warehouse.ConsoleClient.DataService.ShowStatusResponse Warehouse.ConsoleClient.DataService.IDataService.ShowStatus(Warehouse.ConsoleClient.DataService.ShowStatusRequest request) {
            return base.Channel.ShowStatus(request);
        }
        
        public string ShowStatus(out bool success, out string exceptionString) {
            Warehouse.ConsoleClient.DataService.ShowStatusRequest inValue = new Warehouse.ConsoleClient.DataService.ShowStatusRequest();
            Warehouse.ConsoleClient.DataService.ShowStatusResponse retVal = ((Warehouse.ConsoleClient.DataService.IDataService)(this)).ShowStatus(inValue);
            success = retVal.success;
            exceptionString = retVal.exceptionString;
            return retVal.ShowStatusResult;
        }
        
        public System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.ShowStatusResponse> ShowStatusAsync(Warehouse.ConsoleClient.DataService.ShowStatusRequest request) {
            return base.Channel.ShowStatusAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Warehouse.ConsoleClient.DataService.PlaceContainersResponse Warehouse.ConsoleClient.DataService.IDataService.PlaceContainers(Warehouse.ConsoleClient.DataService.PlaceContainersRequest request) {
            return base.Channel.PlaceContainers(request);
        }
        
        public string PlaceContainers(ushort N, out bool success, out string exceptionString) {
            Warehouse.ConsoleClient.DataService.PlaceContainersRequest inValue = new Warehouse.ConsoleClient.DataService.PlaceContainersRequest();
            inValue.N = N;
            Warehouse.ConsoleClient.DataService.PlaceContainersResponse retVal = ((Warehouse.ConsoleClient.DataService.IDataService)(this)).PlaceContainers(inValue);
            success = retVal.success;
            exceptionString = retVal.exceptionString;
            return retVal.PlaceContainersResult;
        }
        
        public System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.PlaceContainersResponse> PlaceContainersAsync(Warehouse.ConsoleClient.DataService.PlaceContainersRequest request) {
            return base.Channel.PlaceContainersAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Warehouse.ConsoleClient.DataService.FreeContainersResponse Warehouse.ConsoleClient.DataService.IDataService.FreeContainers(Warehouse.ConsoleClient.DataService.FreeContainersRequest request) {
            return base.Channel.FreeContainers(request);
        }
        
        public string FreeContainers(ushort N, string hangarId, out bool success, out string exceptionString) {
            Warehouse.ConsoleClient.DataService.FreeContainersRequest inValue = new Warehouse.ConsoleClient.DataService.FreeContainersRequest();
            inValue.N = N;
            inValue.hangarId = hangarId;
            Warehouse.ConsoleClient.DataService.FreeContainersResponse retVal = ((Warehouse.ConsoleClient.DataService.IDataService)(this)).FreeContainers(inValue);
            success = retVal.success;
            exceptionString = retVal.exceptionString;
            return retVal.FreeContainersResult;
        }
        
        public System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.FreeContainersResponse> FreeContainersAsync(Warehouse.ConsoleClient.DataService.FreeContainersRequest request) {
            return base.Channel.FreeContainersAsync(request);
        }
    }
}
