//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.ConsoleClient.DataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Site", Namespace="http://schemas.datacontract.org/2004/07/DataService")]
    [System.SerializableAttribute()]
    public partial class Site : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmptyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Empty {
            get {
                return this.EmptyField;
            }
            set {
                if ((this.EmptyField.Equals(value) != true)) {
                    this.EmptyField = value;
                    this.RaisePropertyChanged("Empty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hangar", Namespace="http://schemas.datacontract.org/2004/07/DataService")]
    [System.SerializableAttribute()]
    public partial class Hangar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FullnessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fullness {
            get {
                return this.FullnessField;
            }
            set {
                if ((this.FullnessField.Equals(value) != true)) {
                    this.FullnessField = value;
                    this.RaisePropertyChanged("Fullness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteId {
            get {
                return this.SiteIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteIdField, value) != true)) {
                    this.SiteIdField = value;
                    this.RaisePropertyChanged("SiteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllSites", ReplyAction="http://tempuri.org/IDataService/GetAllSitesResponse")]
        Warehouse.ConsoleClient.DataService.Site[] GetAllSites();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllSites", ReplyAction="http://tempuri.org/IDataService/GetAllSitesResponse")]
        System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.Site[]> GetAllSitesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetSites", ReplyAction="http://tempuri.org/IDataService/GetSitesResponse")]
        Warehouse.ConsoleClient.DataService.Site[] GetSites(bool empty, bool full);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetSites", ReplyAction="http://tempuri.org/IDataService/GetSitesResponse")]
        System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.Site[]> GetSitesAsync(bool empty, bool full);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/HangarExists", ReplyAction="http://tempuri.org/IDataService/HangarExistsResponse")]
        bool HangarExists(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/HangarExists", ReplyAction="http://tempuri.org/IDataService/HangarExistsResponse")]
        System.Threading.Tasks.Task<bool> HangarExistsAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetHangar", ReplyAction="http://tempuri.org/IDataService/GetHangarResponse")]
        Warehouse.ConsoleClient.DataService.Hangar GetHangar(string hangarId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetHangar", ReplyAction="http://tempuri.org/IDataService/GetHangarResponse")]
        System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.Hangar> GetHangarAsync(string hangarId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllHangars", ReplyAction="http://tempuri.org/IDataService/GetAllHangarsResponse")]
        Warehouse.ConsoleClient.DataService.Hangar[] GetAllHangars(string siteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllHangars", ReplyAction="http://tempuri.org/IDataService/GetAllHangarsResponse")]
        System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.Hangar[]> GetAllHangarsAsync(string siteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetHangars", ReplyAction="http://tempuri.org/IDataService/GetHangarsResponse")]
        Warehouse.ConsoleClient.DataService.Hangar[] GetHangars(string siteId, bool empty, bool full);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetHangars", ReplyAction="http://tempuri.org/IDataService/GetHangarsResponse")]
        System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.Hangar[]> GetHangarsAsync(string siteId, bool empty, bool full);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ModifyHangar", ReplyAction="http://tempuri.org/IDataService/ModifyHangarResponse")]
        bool ModifyHangar(string id, int N);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ModifyHangar", ReplyAction="http://tempuri.org/IDataService/ModifyHangarResponse")]
        System.Threading.Tasks.Task<bool> ModifyHangarAsync(string id, int N);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetFreePlacesCount", ReplyAction="http://tempuri.org/IDataService/GetFreePlacesCountResponse")]
        int GetFreePlacesCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetFreePlacesCount", ReplyAction="http://tempuri.org/IDataService/GetFreePlacesCountResponse")]
        System.Threading.Tasks.Task<int> GetFreePlacesCountAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : Warehouse.ConsoleClient.DataService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<Warehouse.ConsoleClient.DataService.IDataService>, Warehouse.ConsoleClient.DataService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Warehouse.ConsoleClient.DataService.Site[] GetAllSites() {
            return base.Channel.GetAllSites();
        }
        
        public System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.Site[]> GetAllSitesAsync() {
            return base.Channel.GetAllSitesAsync();
        }
        
        public Warehouse.ConsoleClient.DataService.Site[] GetSites(bool empty, bool full) {
            return base.Channel.GetSites(empty, full);
        }
        
        public System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.Site[]> GetSitesAsync(bool empty, bool full) {
            return base.Channel.GetSitesAsync(empty, full);
        }
        
        public bool HangarExists(string id) {
            return base.Channel.HangarExists(id);
        }
        
        public System.Threading.Tasks.Task<bool> HangarExistsAsync(string id) {
            return base.Channel.HangarExistsAsync(id);
        }
        
        public Warehouse.ConsoleClient.DataService.Hangar GetHangar(string hangarId) {
            return base.Channel.GetHangar(hangarId);
        }
        
        public System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.Hangar> GetHangarAsync(string hangarId) {
            return base.Channel.GetHangarAsync(hangarId);
        }
        
        public Warehouse.ConsoleClient.DataService.Hangar[] GetAllHangars(string siteId) {
            return base.Channel.GetAllHangars(siteId);
        }
        
        public System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.Hangar[]> GetAllHangarsAsync(string siteId) {
            return base.Channel.GetAllHangarsAsync(siteId);
        }
        
        public Warehouse.ConsoleClient.DataService.Hangar[] GetHangars(string siteId, bool empty, bool full) {
            return base.Channel.GetHangars(siteId, empty, full);
        }
        
        public System.Threading.Tasks.Task<Warehouse.ConsoleClient.DataService.Hangar[]> GetHangarsAsync(string siteId, bool empty, bool full) {
            return base.Channel.GetHangarsAsync(siteId, empty, full);
        }
        
        public bool ModifyHangar(string id, int N) {
            return base.Channel.ModifyHangar(id, N);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyHangarAsync(string id, int N) {
            return base.Channel.ModifyHangarAsync(id, N);
        }
        
        public int GetFreePlacesCount() {
            return base.Channel.GetFreePlacesCount();
        }
        
        public System.Threading.Tasks.Task<int> GetFreePlacesCountAsync() {
            return base.Channel.GetFreePlacesCountAsync();
        }
    }
}
